" source and call pathogen 
source ~/bin/envfiles/vim/pathogen/autoload/pathogen.vim
call pathogen#infect('~/bin/envfiles/vim/bundle')
call pathogen#helptags()

syntax on
filetype plugin indent on
set number        " show line numbers
set list          " turn on invisible chars
set listchars=tab:▸\ ,trail:▝,eol:¬ " Change the chars used to represents invisibles chars
set smartindent   " automatically inserts one extra level of indentation in some cases
set shiftwidth=4 
set expandtab
set wrap          " wrap lines
set linebreak     " don't break words
set tabstop=4     " a tab is four spaces
set softtabstop=4 " backspace back tab
set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting
set showmatch     " set show matching parenthesis
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type
set title		  " change the terminal's title
set nobackup
set noswapfile
" Easy window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
" Set to auto read when a file is changed from the outside
set autoread
colo blackboard " default colorscheme
" set statusline using powerline plugin
" set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}
set laststatus=2
set nocompatible " Disable vi-compatibility

" Only do this part when compiled with support for autocommands
if has("autocmd")
  " Enable file type detection
  filetype on
   
  " Syntax of these languages is fussy over tabs Vs spaces
  autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
  autocmd FileType yaml,ruby setlocal ts=2 sts=2 sw=2 expandtab
   
  " Customisations based on house-style (arbitrary)
  autocmd FileType html setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType css setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType javascript setlocal ts=4 sts=4 sw=4 noexpandtab
  autocmd FileType cucumber setlocal sw=2 sts=2 et
 
  " Treat .rss files as XML
  autocmd BufNewFile,BufRead *.rss setfiletype xml
endif

let Tlist_Ctags_Cmd = '/usr/local/Cellar/ctags/5.8/bin/ctags'
if has('gui_running')
	  set guifont=Inconsolata:h15
endif
" map space to select word in visualmode
:map <space> viw
